/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.FundsRetrieval;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Organization.Organization;
import Business.Organization.CorporateFundOrg;
import Business.Role.CorporateManagerRole;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.FundingWorkRequest;
import Business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Amey
 */
public class CorporateFundingPanel extends javax.swing.JPanel {

    EcoSystem ecoSystem;
    Enterprise enterprise;
    Organization organization;
    JPanel panel;
    private UserAccount useraccount;
    String patient = null;
    /**
     * Creates new form CorporateFundingPanel
     */
    public CorporateFundingPanel(EcoSystem ecoSystem, Enterprise enterprise, Organization org, JPanel panel, UserAccount useraccount) {
        initComponents();
        this.ecoSystem = ecoSystem;
        this.enterprise = enterprise;
        this.organization = org;
        this.panel = panel;
        this.useraccount = useraccount;
        populateTable();
    }
    
    public void populateTable(){
        
        System.out.println("####LP#### In Corporate Table");
        DefaultTableModel dtm  = (DefaultTableModel)corpEventDetailTable.getModel();
        dtm.setRowCount(0);
        
        for(Organization organization : enterprise.getOrganizationDirectory().getOrganizationList()){  
            System.out.println(organization);
            System.out.println(organization.getWorkQueue().getWorkRequestList());
            if(organization instanceof CorporateFundOrg){
            for(WorkRequest req : organization.getWorkQueue().getWorkRequestList()){
                
            Object[] row = new Object[4];
            row[0] = req;
            row[1] = req.getSender().getEmployee();
            row[2] = req.getReceiver() == null ? null : req.getReceiver().getEmployee().getEmpName();
            row[3] = req.getStatus();
            System.out.println(row[1]);
            System.out.println(row[2]);
            System.out.println(row[3]);
            dtm.addRow(row);
            }
        }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        corpEventFundTableLabel = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        corpEventDetailTable = new javax.swing.JTable();
        assignToMeButton = new javax.swing.JButton();
        processButton = new javax.swing.JButton();

        setBackground(java.awt.SystemColor.activeCaption);

        corpEventFundTableLabel.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        corpEventFundTableLabel.setText("Corporate Event Fund Raising Details");

        corpEventDetailTable.setBackground(java.awt.SystemColor.info);
        corpEventDetailTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Message", "Sender", "Receiver", "Status"
            }
        ));
        jScrollPane3.setViewportView(corpEventDetailTable);

        assignToMeButton.setBackground(java.awt.SystemColor.controlLtHighlight);
        assignToMeButton.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        assignToMeButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UserInterface/Images/icons8-audit-24.png"))); // NOI18N
        assignToMeButton.setText("Assign To Me");
        assignToMeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                assignToMeButtonActionPerformed(evt);
            }
        });

        processButton.setBackground(java.awt.SystemColor.controlLtHighlight);
        processButton.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        processButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UserInterface/Images/process.png"))); // NOI18N
        processButton.setText("Process");
        processButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                processButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(109, 109, 109)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(corpEventFundTableLabel)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(assignToMeButton)
                        .addGap(640, 640, 640)
                        .addComponent(processButton))
                    .addComponent(jScrollPane3))
                .addContainerGap(55, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addComponent(corpEventFundTableLabel)
                .addGap(33, 33, 33)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(assignToMeButton)
                    .addComponent(processButton))
                .addContainerGap(348, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void assignToMeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_assignToMeButtonActionPerformed
        // TODO add your handling code here:
        int selectedRow = corpEventDetailTable.getSelectedRow();

        if(corpEventDetailTable.getRowCount() == 0){
            JOptionPane.showMessageDialog(null, "No rows available to select", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }

        if (selectedRow < 0){
            JOptionPane.showMessageDialog(null, "Please select a row", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }

        WorkRequest request = (WorkRequest)corpEventDetailTable.getValueAt(selectedRow, 0);
        request.setReceiver(useraccount);
        request.setStatus("Pending");
        if(useraccount.getRole() instanceof CorporateManagerRole){
            populateTable();
        }
    }//GEN-LAST:event_assignToMeButtonActionPerformed

    private void processButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_processButtonActionPerformed
        // TODO add your handling code here:
        int selectedRow = corpEventDetailTable.getSelectedRow();

        if(corpEventDetailTable.getRowCount() == 0){
            JOptionPane.showMessageDialog(null, "No rows available to select", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        if (selectedRow < 0){
            JOptionPane.showMessageDialog(null, "Please select a row", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }

        FundingWorkRequest request = (FundingWorkRequest)corpEventDetailTable.getValueAt(selectedRow, 0);
        request.setFundStatus("Processing");
        
        FundsApprovalPanel processWorkRequestJPanel = new FundsApprovalPanel(panel, request, useraccount);
        panel.add("processWorkRequestJPanel", processWorkRequestJPanel);
        CardLayout layout = (CardLayout) panel.getLayout();
        layout.next(panel);
    }//GEN-LAST:event_processButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton assignToMeButton;
    private javax.swing.JTable corpEventDetailTable;
    private javax.swing.JLabel corpEventFundTableLabel;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JButton processButton;
    // End of variables declaration//GEN-END:variables
}
