/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.FundsRetrieval;

import Business.Role.TrustManagerRole;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.FundingWorkRequest;
import java.awt.CardLayout;
import java.awt.Component;
import java.util.Properties;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.mail.Message;
import javax.mail.Session;
import javax.mail.Transport;
import javax.mail.internet.InternetAddress;
import javax.mail.internet.MimeMessage;

/**
 *
 * @author Amey
 */
public class FundsApprovalPanel extends javax.swing.JPanel {

    JPanel panel;
    FundingWorkRequest request;
    UserAccount account;
    /**
     * Creates new form NewJPanel
     */
    public FundsApprovalPanel(JPanel panel, FundingWorkRequest request, UserAccount account ) {
        initComponents();
        this.panel = panel;
        this.request = request;
        this.account = account;
        populateFundAmount();              
    }

    public void populateFundAmount(){
        requestedFundFormTextField.setText(String.valueOf(request.getAmount()));
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        requestedFundFormLabel = new javax.swing.JLabel();
        requestedFundFormTextField = new javax.swing.JTextField();
        approveRequestBtn = new javax.swing.JButton();
        declineRequestBtn = new javax.swing.JButton();
        requestedFundCurrencyLabel = new javax.swing.JLabel();
        backBtn = new javax.swing.JButton();
        approvalPageHelperImage = new javax.swing.JLabel();

        setBackground(java.awt.SystemColor.activeCaption);

        requestedFundFormLabel.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        requestedFundFormLabel.setText("Fund Requested");

        requestedFundFormTextField.setEditable(false);
        requestedFundFormTextField.setEnabled(false);
        requestedFundFormTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                requestedFundFormTextFieldActionPerformed(evt);
            }
        });

        approveRequestBtn.setBackground(java.awt.SystemColor.controlLtHighlight);
        approveRequestBtn.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        approveRequestBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UserInterface/Images/check.png"))); // NOI18N
        approveRequestBtn.setText("Approve Funds Request");
        approveRequestBtn.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        approveRequestBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                approveRequestBtnActionPerformed(evt);
            }
        });

        declineRequestBtn.setBackground(java.awt.SystemColor.controlLtHighlight);
        declineRequestBtn.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        declineRequestBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UserInterface/Images/close.png"))); // NOI18N
        declineRequestBtn.setText("Decline Funds Request");
        declineRequestBtn.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        declineRequestBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                declineRequestBtnActionPerformed(evt);
            }
        });

        requestedFundCurrencyLabel.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        requestedFundCurrencyLabel.setText("$");

        backBtn.setBackground(java.awt.SystemColor.controlLtHighlight);
        backBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UserInterface/Images/left-arrow-in-circular-button-black-symbol-2.png"))); // NOI18N
        backBtn.setText("Back");
        backBtn.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });

        approvalPageHelperImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UserInterface/Images/approved-600x310.jpg"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(261, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(requestedFundCurrencyLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(requestedFundFormTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(declineRequestBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(approveRequestBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(approvalPageHelperImage)
                        .addComponent(requestedFundFormLabel)))
                .addGap(240, 240, 240))
            .addGroup(layout.createSequentialGroup()
                .addGap(89, 89, 89)
                .addComponent(backBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(backBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 77, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(requestedFundCurrencyLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(requestedFundFormTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(requestedFundFormLabel))
                .addGap(94, 94, 94)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(approveRequestBtn)
                    .addComponent(declineRequestBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(89, 89, 89)
                .addComponent(approvalPageHelperImage)
                .addGap(97, 97, 97))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void requestedFundFormTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_requestedFundFormTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_requestedFundFormTextFieldActionPerformed

    private void approveRequestBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_approveRequestBtnActionPerformed
        if(request.getStatus().equalsIgnoreCase("Approved") || request.getStatus().equalsIgnoreCase("Declined")){
            JOptionPane.showMessageDialog(null, "The funds have already been Approved/Declined");
            return;
        }
        
        if(requestedFundFormTextField.getText().equals(""))
        {
            JOptionPane.showMessageDialog(null, "Please enter a comment!");
            return;
        }
        else{
            request.setApproval(requestedFundFormTextField.getText());
 
            final String recipient = request.getSender().toString();//this needs to be an email address
            boolean sessionDebug = false;
            
            String from = "taskplannermernproject@gmail.com";
            String host = "smtp.gmail.com";
            String user="taskplannermernproject@gmail.com";
            String pass = "taskplannermernproject@123";
            Properties prop = System.getProperties();
            prop.setProperty("mail.smtp.host", host); 
            prop.put("mail.smtp.starttls.required", "true");
            prop.put("mail.smtp.starttls.enable", "true");
            prop.put("mail.smtp.host", host);
            prop.put("mail.smtp.port", "587");
            prop.put("mail.smtp.auth", "true");
            
            java.security.Security.addProvider(new com.sun.net.ssl.internal.ssl.Provider());
            
            Session session;
            session = Session.getDefaultInstance(prop, null);
            session.setDebug(sessionDebug);
            
            try{
                MimeMessage msg = new MimeMessage(session);
                msg.setFrom(new InternetAddress(from));
                msg.setRecipient(Message.RecipientType.TO,new InternetAddress(recipient));
                InternetAddress address;
                address = new InternetAddress(recipient);
                msg.setSubject("Status of the Fund Approval");
                msg.setText("The requested fund has been approved");
                Transport transport = session.getTransport("smtp");
                transport.connect(host,user,pass);
                transport.sendMessage(msg, msg.getAllRecipients());
                transport.close();
                }catch(Exception ex){
                    JOptionPane.showMessageDialog(null, "Error encountered while sending email");
                }   

            request.setStatus("Approved");
            JOptionPane.showMessageDialog(null, "Funds have been approved");
        }
    }//GEN-LAST:event_approveRequestBtnActionPerformed

    private void declineRequestBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_declineRequestBtnActionPerformed
        // TODO add your handling code here:
        if(request.getStatus().equalsIgnoreCase("Approved") || request.getStatus().equalsIgnoreCase("Declined")){
            JOptionPane.showMessageDialog(null, "The funds have already been Approved/Declined");
            return;
        }
        
        if(requestedFundFormTextField.getText().equals(""))
        {
            JOptionPane.showMessageDialog(null, "Please enter a comment!");
            return;
        }
        else{
            request.setApproval(requestedFundFormTextField.getText());
 
            final String recipient = request.getSender().toString();//this needs to be an email address
            boolean sessionDebug = false;
            
            String from = "taskplannermernproject@gmail.com";
            String host = "smtp.gmail.com";
            String user="taskplannermernproject@gmail.com";
            String pass = "taskplannermernproject@123";
            Properties prop = System.getProperties();
            prop.setProperty("mail.smtp.host", host); 
            prop.put("mail.smtp.starttls.required", "true");
            prop.put("mail.smtp.starttls.enable", "true");
            prop.put("mail.smtp.host", host);
            prop.put("mail.smtp.port", "587");
            prop.put("mail.smtp.auth", "true");
            
            java.security.Security.addProvider(new com.sun.net.ssl.internal.ssl.Provider());
            
            Session session;
            session = Session.getDefaultInstance(prop, null);
            session.setDebug(sessionDebug);
            
            try{
                MimeMessage msg = new MimeMessage(session);
                msg.setFrom(new InternetAddress(from));
                msg.setRecipient(Message.RecipientType.TO,new InternetAddress(recipient));
                InternetAddress address;
                address = new InternetAddress(recipient);
                msg.setSubject("Status of the Fund Approval");
                msg.setText("The requested fund has been declined");
                Transport transport = session.getTransport("smtp");
                transport.connect(host,user,pass);
                transport.sendMessage(msg, msg.getAllRecipients());
                transport.close();
                }catch(Exception ex){
                    JOptionPane.showMessageDialog(null, "Error encountered while sending email");
                }   

            request.setStatus("Declined");
            JOptionPane.showMessageDialog(null, "Funds have been declined");
        }
        
    }//GEN-LAST:event_declineRequestBtnActionPerformed

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        // TODO add your handling code here:
        panel.remove(this);
        Component[] componentArray = panel.getComponents();
        Component component = componentArray[componentArray.length - 1];
        GovtFundingPanel cont = (GovtFundingPanel) component;
        if(account.getRole() instanceof TrustManagerRole)
        cont.populateTable();       
        CardLayout layout = (CardLayout) panel.getLayout();
        layout.previous(panel);
    }//GEN-LAST:event_backBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel approvalPageHelperImage;
    private javax.swing.JButton approveRequestBtn;
    private javax.swing.JButton backBtn;
    private javax.swing.JButton declineRequestBtn;
    private javax.swing.JLabel requestedFundCurrencyLabel;
    private javax.swing.JLabel requestedFundFormLabel;
    private javax.swing.JTextField requestedFundFormTextField;
    // End of variables declaration//GEN-END:variables
}