/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.FundsRetrieval;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Entity.ApplicantDirectory;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.FundingWorkRequest;
import Business.WorkQueue.WorkRequest;
import UserInterface.Campaign.AwarenessCampaignInitiator;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Amey
 */
public class FundsRequestStatusPanel extends javax.swing.JPanel {

    EcoSystem ecoSystem;
    JPanel panel;
    private Enterprise enterprise;
    private UserAccount userAccount;    
    ApplicantDirectory applicant = new ApplicantDirectory();
    
    /**
     * Creates new form FundsRequestStatusPanel
     */
    public FundsRequestStatusPanel(Enterprise enterprise, JPanel panel, UserAccount userAccount) {
        initComponents();
        this.enterprise = enterprise;
        this.panel = panel;
        this.userAccount = userAccount;
        
        populateTrustFundsRequestTable();
        populatecorporateFundsRequestTable();
    }
    
    public void populateTrustFundsRequestTable(){
        DefaultTableModel dtm = (DefaultTableModel)governmentFundRequestStatusTable.getModel();
        dtm.setRowCount(0);
        
        FundingWorkRequest req = new FundingWorkRequest();
        for (WorkRequest request : userAccount.getWorkQueue().getWorkRequestList()){
            Object[] row = new Object[4];
            row[0] = ((FundingWorkRequest) request).getCampaign();
            row[1] = ((FundingWorkRequest) request).getReceiver();
            row[2] = ((FundingWorkRequest) request).getFundStatus();
            String result = String.valueOf(((FundingWorkRequest) request).getAmount());
            row[3] = result;
            dtm.addRow(row);
        }
    }
    
    public void populatecorporateFundsRequestTable(){
        DefaultTableModel dtm = (DefaultTableModel)governmentFundRequestStatusTable1.getModel();
        dtm.setRowCount(0);
        
        FundingWorkRequest req = new FundingWorkRequest();
        for (WorkRequest request : userAccount.getWorkQueue().getWorkRequestList()){
            Object[] row = new Object[4];
            row[0] = ((FundingWorkRequest) request).getCampaign();
            row[1] = ((FundingWorkRequest) request).getReceiver();
            row[2] = ((FundingWorkRequest) request).getFundStatus();
            String result = String.valueOf(((FundingWorkRequest) request).getAmount());
            row[3] = result;
            dtm.addRow(row);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        governmentFundRequestStatusTable = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        governmentFundRequestStatusTable1 = new javax.swing.JTable();
        govtFundingTableHeaderLbl = new javax.swing.JLabel();
        corporateFundingTableHeaderLbl = new javax.swing.JLabel();
        backBtn = new javax.swing.JButton();

        setBackground(new java.awt.Color(204, 204, 255));

        governmentFundRequestStatusTable.setBackground(java.awt.SystemColor.info);
        governmentFundRequestStatusTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Event Name", "Sender", "Status", "Funds"
            }
        ));
        jScrollPane1.setViewportView(governmentFundRequestStatusTable);

        governmentFundRequestStatusTable1.setBackground(java.awt.SystemColor.info);
        governmentFundRequestStatusTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Event Name", "Sender", "Status", "Funds"
            }
        ));
        jScrollPane3.setViewportView(governmentFundRequestStatusTable1);

        govtFundingTableHeaderLbl.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        govtFundingTableHeaderLbl.setText("Trust Funds Request Status");

        corporateFundingTableHeaderLbl.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        corporateFundingTableHeaderLbl.setText("Corporate Funds Request Status");

        backBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UserInterface/Images/left-arrow-in-circular-button-black-symbol-2.png"))); // NOI18N
        backBtn.setText("BACK");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(147, 147, 147)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(backBtn)
                    .addComponent(corporateFundingTableHeaderLbl)
                    .addComponent(govtFundingTableHeaderLbl)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 850, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 850, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(110, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(backBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE)
                .addComponent(govtFundingTableHeaderLbl)
                .addGap(36, 36, 36)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47)
                .addComponent(corporateFundingTableHeaderLbl)
                .addGap(42, 42, 42)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        // TODO add your handling code here:
        panel.remove(this);
        CardLayout layout = (CardLayout)panel.getLayout();
        layout.previous(panel);
    }//GEN-LAST:event_backBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backBtn;
    private javax.swing.JLabel corporateFundingTableHeaderLbl;
    private javax.swing.JTable governmentFundRequestStatusTable;
    private javax.swing.JTable governmentFundRequestStatusTable1;
    private javax.swing.JLabel govtFundingTableHeaderLbl;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    // End of variables declaration//GEN-END:variables
}
