/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.FundsRetrieval;

/**
 *
 * @author Amey
 */
public class FundsRequestStatusPanel extends javax.swing.JPanel {

    /**
     * Creates new form FundsRequestStatusPanel
     */
    public FundsRequestStatusPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        governmentFundRequestStatusTable = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        governmentFundRequestStatusTable1 = new javax.swing.JTable();
        govtFundingTableHeaderLbl = new javax.swing.JLabel();
        corporateFundingTableHeaderLbl = new javax.swing.JLabel();
        backBtn = new javax.swing.JButton();

        setBackground(new java.awt.Color(204, 204, 255));

        governmentFundRequestStatusTable.setBackground(new java.awt.Color(0, 153, 255));
        governmentFundRequestStatusTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Event Name", "Sender", "Status", "Funds"
            }
        ));
        jScrollPane1.setViewportView(governmentFundRequestStatusTable);

        governmentFundRequestStatusTable1.setBackground(new java.awt.Color(0, 153, 255));
        governmentFundRequestStatusTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Event Name", "Sender", "Status", "Funds"
            }
        ));
        jScrollPane3.setViewportView(governmentFundRequestStatusTable1);

        govtFundingTableHeaderLbl.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        govtFundingTableHeaderLbl.setText("Government Funds Request Status");

        corporateFundingTableHeaderLbl.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        corporateFundingTableHeaderLbl.setText("Corporate Funds Request Status");

        backBtn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        backBtn.setText("<<BACK");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(147, 147, 147)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(backBtn)
                    .addComponent(corporateFundingTableHeaderLbl)
                    .addComponent(govtFundingTableHeaderLbl)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 850, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 850, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(110, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(backBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 57, Short.MAX_VALUE)
                .addComponent(govtFundingTableHeaderLbl)
                .addGap(36, 36, 36)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47)
                .addComponent(corporateFundingTableHeaderLbl)
                .addGap(42, 42, 42)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backBtn;
    private javax.swing.JLabel corporateFundingTableHeaderLbl;
    private javax.swing.JTable governmentFundRequestStatusTable;
    private javax.swing.JTable governmentFundRequestStatusTable1;
    private javax.swing.JLabel govtFundingTableHeaderLbl;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    // End of variables declaration//GEN-END:variables
}
