/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.FundsRetrieval;

/**
 *
 * @author Amey
 */
public class GovtFundingPanel extends javax.swing.JPanel {

    /**
     * Creates new form GovtFundingPanel
     */
    public GovtFundingPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        govtEventDetailTable = new javax.swing.JTable();
        govtEventFundTableLabel = new javax.swing.JLabel();
        assignToMeButton = new javax.swing.JButton();
        processButton = new javax.swing.JButton();

        setBackground(new java.awt.Color(204, 204, 255));

        govtEventDetailTable.setBackground(new java.awt.Color(0, 153, 255));
        govtEventDetailTable.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        govtEventDetailTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Message", "Sender", "Receiver", "Status"
            }
        ));
        jScrollPane1.setViewportView(govtEventDetailTable);

        govtEventFundTableLabel.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        govtEventFundTableLabel.setText("Government Event Fund Raising Details");

        assignToMeButton.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        assignToMeButton.setText("Assign To Me");

        processButton.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        processButton.setText("Process");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 101, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(govtEventFundTableLabel)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 914, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(83, 83, 83))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(286, Short.MAX_VALUE)
                .addComponent(assignToMeButton)
                .addGap(223, 223, 223)
                .addComponent(processButton)
                .addGap(315, 315, 315))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(govtEventFundTableLabel)
                .addGap(34, 34, 34)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(96, 96, 96)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(assignToMeButton)
                    .addComponent(processButton))
                .addContainerGap(368, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton assignToMeButton;
    private javax.swing.JTable govtEventDetailTable;
    private javax.swing.JLabel govtEventFundTableLabel;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton processButton;
    // End of variables declaration//GEN-END:variables
}
