/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.CommonUI;

import Business.Employee.Employee;
import Business.Enterprise.Enterprise;
import Business.Organization.Organization;
import Business.Utils.Utils;
import UserInterface.HospitalAdminWorkspace.ManageHospitalApplicant;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Amey
 */
public class ManageEmployeeReusablePanel extends javax.swing.JPanel {

    JPanel rightJPanel;
    private Enterprise enterpriseObj;

    /**
     * Creates new form ManageEmployeeReusablePanel
     */
    public ManageEmployeeReusablePanel(JPanel rightJPanel, Enterprise enterpriseObj) {
        initComponents();
        this.rightJPanel = rightJPanel;
        this.enterpriseObj = enterpriseObj;
        populateOrgDropDown();
    }
    
    private void populateOrgDropDown() {
        sortByDropdown.removeAllItems();
        organizationDropdown.removeAllItems();
        for (Organization organization : enterpriseObj.getOrganizationDirectory().getOrganizationList()) {
            sortByDropdown.addItem(organization);
            organizationDropdown.addItem(organization);
        }
    }

    private void populateEmployeeTable(Organization org) {
        DefaultTableModel tableModel = (DefaultTableModel)displayEmployeeDetailsTable.getModel();
        tableModel.setRowCount(0);
        for (Employee employeeObj : org.getEmployeeDirectory().getEmpList()) {
            Object[] row = new Object[2];
            row[0] = employeeObj.getEmpID();
            row[1] = employeeObj.getEmpName();
            tableModel.addRow(row);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sortByDropdownLabel = new javax.swing.JLabel();
        sortByDropdown = new javax.swing.JComboBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        displayEmployeeDetailsTable = new javax.swing.JTable();
        organizationDropdown = new javax.swing.JComboBox();
        nameTextField = new javax.swing.JTextField();
        nameTextFieldLabel = new javax.swing.JLabel();
        organizationDropdownLabel = new javax.swing.JLabel();
        backButton = new javax.swing.JButton();
        addButton = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        sortByDropdownLabel.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        sortByDropdownLabel.setText("Sort by");
        add(sortByDropdownLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 90, -1, 30));

        sortByDropdown.setFont(new java.awt.Font("Times New Roman", 1, 23)); // NOI18N
        sortByDropdown.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        sortByDropdown.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sortByDropdownActionPerformed(evt);
            }
        });
        add(sortByDropdown, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 90, 380, -1));

        displayEmployeeDetailsTable.setBackground(new java.awt.Color(255, 204, 204));
        displayEmployeeDetailsTable.setFont(new java.awt.Font("Times New Roman", 1, 23)); // NOI18N
        displayEmployeeDetailsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "ID", "Name"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(displayEmployeeDetailsTable);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 150, 980, 170));

        organizationDropdown.setFont(new java.awt.Font("Times New Roman", 1, 23)); // NOI18N
        organizationDropdown.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        organizationDropdown.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                organizationDropdownMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                organizationDropdownMouseEntered(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                organizationDropdownMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                organizationDropdownMouseReleased(evt);
            }
        });
        organizationDropdown.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                organizationDropdownActionPerformed(evt);
            }
        });
        add(organizationDropdown, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 370, 270, 40));

        nameTextField.setFont(new java.awt.Font("Times New Roman", 1, 23)); // NOI18N
        add(nameTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 440, 270, 40));

        nameTextFieldLabel.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        nameTextFieldLabel.setText("Name");
        add(nameTextFieldLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 450, -1, -1));

        organizationDropdownLabel.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        organizationDropdownLabel.setText("Organization");
        add(organizationDropdownLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 380, -1, -1));

        backButton.setBackground(new java.awt.Color(153, 204, 255));
        backButton.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        backButton.setText("<< Back");
        backButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });
        add(backButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 20, 160, 50));

        addButton.setBackground(new java.awt.Color(153, 204, 255));
        addButton.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        addButton.setText("Add ");
        addButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });
        add(addButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 570, 180, 50));
    }// </editor-fold>//GEN-END:initComponents

    private void sortByDropdownActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sortByDropdownActionPerformed

    }//GEN-LAST:event_sortByDropdownActionPerformed

    private void organizationDropdownMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_organizationDropdownMouseClicked

    }//GEN-LAST:event_organizationDropdownMouseClicked

    private void organizationDropdownMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_organizationDropdownMouseEntered

    }//GEN-LAST:event_organizationDropdownMouseEntered

    private void organizationDropdownMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_organizationDropdownMousePressed

    }//GEN-LAST:event_organizationDropdownMousePressed

    private void organizationDropdownMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_organizationDropdownMouseReleased

    }//GEN-LAST:event_organizationDropdownMouseReleased

    private void organizationDropdownActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_organizationDropdownActionPerformed
        if (String.valueOf(organizationDropdown.getItemAt(organizationDropdown.getSelectedIndex())).equals("Applicant Org")) {
            nameTextField.setEnabled(false);
            nameTextField.setEditable(false);
        } else {
            nameTextField.setEnabled(true);
            nameTextField.setEditable(true);
        }
    }//GEN-LAST:event_organizationDropdownActionPerformed

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        // TODO add your handling code here:
        rightJPanel.remove(this);
        CardLayout layout = (CardLayout) rightJPanel.getLayout();
        layout.previous(rightJPanel);

    }//GEN-LAST:event_backButtonActionPerformed

    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
        Utils util = new Utils();
        Organization org = (Organization) organizationDropdown.getSelectedItem();
        if((!util.notNullOrEmpty(nameTextField.getText()) || !util.isValidName(nameTextField.getText())) 
                && !org.getName().equals("Applicant Org")) {
            JOptionPane.showMessageDialog(null, "Please enter valid name.");
            return;
        }
       if (org.getName().equals("Applicant Org")) {
            ManageHospitalApplicant hospitalApplicantScreen = new ManageHospitalApplicant(rightJPanel, org);
            rightJPanel.add("hospitalApplicantScreen", hospitalApplicantScreen);
            CardLayout layout = (CardLayout) rightJPanel.getLayout();
            layout.next(rightJPanel);
        } else {
            org.getEmployeeDirectory().createEmployee(nameTextField.getText());
            populateEmployeeTable(org);
            JOptionPane.showMessageDialog(null, "Employee added successfully!");
        }
        nameTextField.setText("");
    }//GEN-LAST:event_addButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addButton;
    private javax.swing.JButton backButton;
    private javax.swing.JTable displayEmployeeDetailsTable;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField nameTextField;
    private javax.swing.JLabel nameTextFieldLabel;
    private javax.swing.JComboBox organizationDropdown;
    private javax.swing.JLabel organizationDropdownLabel;
    private javax.swing.JComboBox sortByDropdown;
    private javax.swing.JLabel sortByDropdownLabel;
    // End of variables declaration//GEN-END:variables
}
