/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.CommonUI;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Enterprise.HospitalEnterprise;
import Business.Organization.Organization;
import Business.Organization.OrganizationDirectory;
import Business.UserAccount.UserAccount;
import UserInterface.HospitalAdminWorkspace.CheckDonorRecipientRatio;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Amey
 */
public class OrganizationAdminReusableWorkArea extends javax.swing.JPanel {
    
    EcoSystem system;
    Enterprise enterpriseObj;
    JPanel rightJPanel;
    UserAccount account;

    /**
     * Creates new form OrganizationAdminReusableWorkArea
     */
    public OrganizationAdminReusableWorkArea( EcoSystem system,JPanel rightJPanel, Enterprise enterprise, UserAccount account) {
        initComponents();
        this.system = system;
        this.rightJPanel = rightJPanel;
        this.enterpriseObj = enterprise;
        this.account = account;
        adminValue.setText(enterpriseObj.getName());
//        if(enterpriseObj instanceof HospitalEnterprise){
//            jButton1.setEnabled(true);
//        }else{
//            jButton1.setEnabled(false);
//        }
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        managePeopleButton = new javax.swing.JButton();
        manageOrgButton = new javax.swing.JButton();
        hospitalAdminLabel = new javax.swing.JLabel();
        adminValue = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        manageUserButton1 = new javax.swing.JButton();
        manageUserButton2 = new javax.swing.JButton();
        checkRatioBtn = new javax.swing.JButton();

        setBackground(java.awt.SystemColor.activeCaption);
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        managePeopleButton.setBackground(java.awt.SystemColor.controlLtHighlight);
        managePeopleButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        managePeopleButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UserInterface/Images/management.png"))); // NOI18N
        managePeopleButton.setText(" Manage People In Organization  ");
        managePeopleButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        managePeopleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                managePeopleButtonActionPerformed(evt);
            }
        });
        add(managePeopleButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 260, 570, 40));

        manageOrgButton.setBackground(java.awt.SystemColor.controlLtHighlight);
        manageOrgButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        manageOrgButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UserInterface/Images/planning.png"))); // NOI18N
        manageOrgButton.setText(" Manage Organization In Enterprise");
        manageOrgButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        manageOrgButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageOrgButtonActionPerformed(evt);
            }
        });
        add(manageOrgButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 200, 570, 40));

        hospitalAdminLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        hospitalAdminLabel.setText("Admin :");
        add(hospitalAdminLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 160, -1, -1));

        adminValue.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        adminValue.setText("<value>");
        add(adminValue, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 160, 430, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Enterprise Admin Screen");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 30, -1, -1));

        manageUserButton1.setBackground(java.awt.SystemColor.controlLtHighlight);
        manageUserButton1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        manageUserButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UserInterface/Images/team-management.png"))); // NOI18N
        manageUserButton1.setText(" Manage User In Organization    ");
        manageUserButton1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        manageUserButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageUserButton1ActionPerformed(evt);
            }
        });
        add(manageUserButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 330, 570, 40));

        manageUserButton2.setBackground(java.awt.SystemColor.controlLtHighlight);
        manageUserButton2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        manageUserButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UserInterface/Images/team-management.png"))); // NOI18N
        manageUserButton2.setText(" Manage User In Organization    ");
        manageUserButton2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        manageUserButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageUserButton2ActionPerformed(evt);
            }
        });
        add(manageUserButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 330, 570, 40));

        checkRatioBtn.setBackground(java.awt.SystemColor.controlLtHighlight);
        checkRatioBtn.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        checkRatioBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UserInterface/Images/team-management.png"))); // NOI18N
        checkRatioBtn.setText("  Check Donor Receipient Ratio");
        checkRatioBtn.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        checkRatioBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkRatioBtnActionPerformed(evt);
            }
        });
        add(checkRatioBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 400, 570, 40));
    }// </editor-fold>//GEN-END:initComponents

    private void managePeopleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_managePeopleButtonActionPerformed
        if(enterpriseObj.getOrganizationDirectory().getOrganizationList().isEmpty()){
            JOptionPane.showMessageDialog(null, "Currently there are no organizations. Please create an organization first.");
            return;
        }
        ManageEmployeeReusablePanel managePeopleJPanel = new ManageEmployeeReusablePanel(rightJPanel, enterpriseObj);
        rightJPanel.add("manageEmployeeRuseableJPanel", managePeopleJPanel);
        CardLayout layout = (CardLayout) rightJPanel.getLayout();
        layout.next(rightJPanel);
    }//GEN-LAST:event_managePeopleButtonActionPerformed

    private void manageOrgButtonActionPerformed(java.awt.event.ActionEvent evt) {                                                
        ManageOrganizationReusablePanel manageOrgaJpanel = new ManageOrganizationReusablePanel(rightJPanel, enterpriseObj);
        rightJPanel.add("manageOrgJpanel", manageOrgaJpanel);
        CardLayout layout = (CardLayout) rightJPanel.getLayout();
        layout.next(rightJPanel);

    }
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        CheckDonorRecipientRatio checkRatio = new CheckDonorRecipientRatio(system, rightJPanel, account, enterpriseObj);
        rightJPanel.add("manageEntAdmins", checkRatio);
        CardLayout layout = (CardLayout) rightJPanel.getLayout();
        layout.next(rightJPanel);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void manageUserButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageUserButton1ActionPerformed
        // TODO add your handling code here:
          if(enterpriseObj.getOrganizationDirectory().getOrganizationList().isEmpty()){
            JOptionPane.showMessageDialog(null, "Currently there are no organizations. Please create organizations first.");
            return;
        }
      
        for(Organization orgObj : enterpriseObj.getOrganizationDirectory().getOrganizationList()){
            if(!orgObj.getEmployeeDirectory().getEmpList().isEmpty()){
                ManageUserAccountReusablePanel manageUserJPanel = new ManageUserAccountReusablePanel(rightJPanel, enterpriseObj);
                rightJPanel.add("manageUserJPanel", manageUserJPanel);
                CardLayout layout = (CardLayout) rightJPanel.getLayout();
                layout.next(rightJPanel);
                return;
            }
                
        }
        JOptionPane.showMessageDialog(null, "Please create employees before creating users."); 
    }//GEN-LAST:event_manageUserButton1ActionPerformed

    private void manageUserButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageUserButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_manageUserButton2ActionPerformed

    private void checkRatioBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkRatioBtnActionPerformed
        // TODO add your handling code here:
        CheckDonorRecipientRatio checkRatio = new CheckDonorRecipientRatio(system, rightJPanel, account, enterpriseObj);
        rightJPanel.add("manageEntAdmins", checkRatio);
        CardLayout layout = (CardLayout) rightJPanel.getLayout();
        layout.next(rightJPanel);
    }//GEN-LAST:event_checkRatioBtnActionPerformed

                                                



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel adminValue;
    private javax.swing.JButton checkRatioBtn;
    private javax.swing.JLabel hospitalAdminLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton manageOrgButton;
    private javax.swing.JButton managePeopleButton;
    private javax.swing.JButton manageUserButton1;
    private javax.swing.JButton manageUserButton2;
    // End of variables declaration//GEN-END:variables
}
