/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.CommonUI;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.WorkQueue.DonorValidationWorkRequest;
import Business.WorkQueue.WorkRequest;
import UserInterface.HospitalAdminWorkspace.ManageHospitalApplicant;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ninos
 */
public class ViewDonorValidationDashboard extends javax.swing.JPanel {

    /**
     * Creates new form ViewDonorValidationDashboard
     */
    EcoSystem system;
    Enterprise enterpriseObj;
    JPanel rightJPanel;
    
    public ViewDonorValidationDashboard(JPanel rightJPanel, Enterprise enterpriseObj ) {
        initComponents();
        this.rightJPanel = rightJPanel;
        this.enterpriseObj = enterpriseObj;
        populateDonorValidationReqTable();
    }
    
    void populateDonorValidationReqTable(){
        DefaultTableModel model = (DefaultTableModel) validateWr.getModel();
        int fitDonorCount = 0;
        int totalDonorCount = 0;
        model.setRowCount(0);
        for(WorkRequest obj : enterpriseObj.getWorkQueue().getWorkRequestList()){
            if(obj instanceof DonorValidationWorkRequest){
                DonorValidationWorkRequest finalobj = (DonorValidationWorkRequest) obj;
                Object[] row = new Object[5];
                row[0] = finalobj;
                row[1] = finalobj.getPatientId();
                row[2] = finalobj.getSender();
                row[3] = finalobj.getReceiver() == null ? "Unassigned" : finalobj.getReceiver();
                row[4] = finalobj.getStatus();
                model.addRow(row); 
                if("Donor Fit".equalsIgnoreCase(finalobj.getTestResult())){
                    fitDonorCount ++;
                }
                totalDonorCount++;
            }
        }
        totalDonors.setText(String.valueOf(totalDonorCount));
        totalFitDonors.setText(String.valueOf(fitDonorCount));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        displayEnterpriseLabel4 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        validateWr = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        totalDonors = new javax.swing.JLabel();
        totalFitDonors = new javax.swing.JLabel();
        backButton = new javax.swing.JButton();

        setBackground(java.awt.SystemColor.activeCaption);

        displayEnterpriseLabel4.setFont(new java.awt.Font("Tahoma", 1, 21)); // NOI18N
        displayEnterpriseLabel4.setText("Donor Validation Work Requests");

        validateWr.setBackground(java.awt.SystemColor.info);
        validateWr.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        validateWr.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Message", "Donor Id", "Sender", "Receiver", "Status", "Test Results"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(validateWr);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Total Fit Donors: ");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("Total Donors: ");

        totalDonors.setBackground(new java.awt.Color(255, 255, 255));
        totalDonors.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        totalDonors.setText("<totalDonrs>");

        totalFitDonors.setBackground(new java.awt.Color(255, 255, 255));
        totalFitDonors.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        totalFitDonors.setText("<totalFitDonors>");

        backButton.setBackground(java.awt.SystemColor.controlLtHighlight);
        backButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UserInterface/Images/left-arrow-in-circular-button-black-symbol-2.png"))); // NOI18N
        backButton.setText("Back");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(backButton, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(144, 144, 144)
                        .addComponent(displayEnterpriseLabel4)
                        .addGap(0, 307, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(totalDonors)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(totalFitDonors)
                                .addGap(18, 18, 18))
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel1)))
                        .addGap(33, 33, 33))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(backButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(displayEnterpriseLabel4))
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1))
                .addGap(1, 1, 1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(totalDonors)
                    .addComponent(totalFitDonors))
                .addGap(44, 44, 44)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(202, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        // TODO add your handling code here:
        rightJPanel.remove(this);
        Component[] componentArray = rightJPanel.getComponents();
        Component component = componentArray[componentArray.length - 1];
        ManageHospitalApplicant manageHospital = (ManageHospitalApplicant) component;
        CardLayout cardLayout = (CardLayout) rightJPanel.getLayout();
        cardLayout.previous(rightJPanel);
    }//GEN-LAST:event_backButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backButton;
    private javax.swing.JLabel displayEnterpriseLabel4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel totalDonors;
    private javax.swing.JLabel totalFitDonors;
    private javax.swing.JTable validateWr;
    // End of variables declaration//GEN-END:variables
}
