/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.SystemAdminWorkspace;

import Business.EcoSystem;
import Business.Network.Network;
import Business.Utils.Utils;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Amey
 */
public class ManageCitiesNetwork extends javax.swing.JPanel {

    EcoSystem ecoSystem;
    JPanel rightJPanel;
    Utils util = new Utils();

    /**
     * Creates new form ManageCitiesNetwork
     */
    public ManageCitiesNetwork(JPanel rightJPanel, EcoSystem ecoSystemObj) {
        initComponents();
        this.ecoSystem = ecoSystemObj;
        this.rightJPanel = rightJPanel;
        populateNetworkTable();
    }

    private void populateNetworkTable() {
        DefaultTableModel networkTable = (DefaultTableModel) citiesNetworkTable.getModel();
        networkTable.setRowCount(0);
        // hide column networks table column
        citiesNetworkTable.getColumnModel().getColumn(1).setMinWidth(0);
        citiesNetworkTable.getColumnModel().getColumn(1).setMaxWidth(0);
        for (Network network : ecoSystem.getNetworks()) {
            Object[] tableRow = new Object[2];
            tableRow[0] = network.getName();
            tableRow[1] = network;
            networkTable.addRow(tableRow);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        citiesNetworkTable = new javax.swing.JTable();
        cityNameTextField = new javax.swing.JTextField();
        cityNameLabel = new javax.swing.JLabel();
        backBtn = new javax.swing.JButton();
        submitBtn = new javax.swing.JButton();
        cityNameLabel1 = new javax.swing.JLabel();
        deleteBtn = new javax.swing.JButton();
        updateBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setBackground(java.awt.SystemColor.activeCaption);

        citiesNetworkTable.setBackground(java.awt.SystemColor.info);
        citiesNetworkTable.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        citiesNetworkTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "City Network Name", "Object"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        citiesNetworkTable.setColumnSelectionAllowed(true);
        jScrollPane2.setViewportView(citiesNetworkTable);
        citiesNetworkTable.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        if (citiesNetworkTable.getColumnModel().getColumnCount() > 0) {
            citiesNetworkTable.getColumnModel().getColumn(1).setResizable(false);
        }

        cityNameTextField.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        cityNameLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        cityNameLabel.setText("Current Networks");

        backBtn.setBackground(java.awt.SystemColor.controlLtHighlight);
        backBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UserInterface/Images/left-arrow-in-circular-button-black-symbol-2.png"))); // NOI18N
        backBtn.setText("Back");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });

        submitBtn.setBackground(java.awt.SystemColor.controlLtHighlight);
        submitBtn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        submitBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UserInterface/Images/icons8-submit-resume-24.png"))); // NOI18N
        submitBtn.setText("Submit");
        submitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitBtnActionPerformed(evt);
            }
        });

        cityNameLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        cityNameLabel1.setText("Create New City Network");

        deleteBtn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        deleteBtn.setText("Delete");
        deleteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteBtnActionPerformed(evt);
            }
        });

        updateBtn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        updateBtn.setText("Update");
        updateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateBtnActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Manage Networks");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 528, Short.MAX_VALUE)
                            .addComponent(cityNameTextField))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(updateBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 123, Short.MAX_VALUE)
                                .addComponent(deleteBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(submitBtn))
                        .addGap(0, 77, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cityNameLabel)
                            .addComponent(cityNameLabel1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(backBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(146, 146, 146)
                                .addComponent(jLabel1)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(backBtn)
                    .addComponent(jLabel1))
                .addGap(77, 77, 77)
                .addComponent(cityNameLabel1)
                .addGap(1, 1, 1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cityNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(submitBtn))
                .addGap(131, 131, 131)
                .addComponent(cityNameLabel)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(deleteBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(updateBtn)))
                .addContainerGap(198, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        // TODO add your handling code here:
        rightJPanel.remove(this);
        Component[] componentArray = rightJPanel.getComponents();
        Component componentObj = componentArray[componentArray.length - 1];
        SystemAdminDashboard sysAdminScreen = (SystemAdminDashboard) componentObj;
        CardLayout prevLayout = (CardLayout) rightJPanel.getLayout();
        // populate tree on admin screen
        sysAdminScreen.populateTree();
        prevLayout.previous(rightJPanel);
    }//GEN-LAST:event_backBtnActionPerformed

    private void submitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitBtnActionPerformed
        // TODO add your handling code here:
        String networkName = cityNameTextField.getText();
        if (util.notNullOrEmpty(networkName)) {
            if (util.isValidName(networkName)) {
                for (Network network : ecoSystem.getNetworks()) {
                    if (network.getName().equalsIgnoreCase(networkName)) {
                        JOptionPane.showMessageDialog(null, "City already exists. Please enter a new city!", "Error", JOptionPane.ERROR_MESSAGE);
                        cityNameTextField.setText("");
                        return;
                    }
                }
                System.out.println("Creating a new network with name :" + networkName);
                Network newNetwork = ecoSystem.createAddNetwork();
                newNetwork.setName(networkName);
                populateNetworkTable();
                System.out.println("Successfully created new network with name :" + networkName);
                cityNameTextField.setText("");
                JOptionPane.showMessageDialog(null, "Sucessfully created a city.", "INFO", JOptionPane.INFORMATION_MESSAGE);
                return;
            }
            JOptionPane.showMessageDialog(null, "Please enter a valid city.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        JOptionPane.showMessageDialog(this, "Please do not leave city name as empty!", "Error", JOptionPane.ERROR_MESSAGE);
    }//GEN-LAST:event_submitBtnActionPerformed

    private void deleteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteBtnActionPerformed
        // TODO add your handling code here:
        int selectedRow = citiesNetworkTable.getSelectedRow();
        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(this, "Please select a city to be deleted", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        Network networkToBeDeleted = (Network) citiesNetworkTable.getValueAt(selectedRow, 1);
        ecoSystem.deleteNetwork(networkToBeDeleted);
        populateNetworkTable();
        JOptionPane.showMessageDialog(null, "Sucessfully deleted city network.", "INFO", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_deleteBtnActionPerformed

    private void updateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateBtnActionPerformed
        // TODO add your handling code here:
        int selectedRow = citiesNetworkTable.getSelectedRow();
        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(this, "Please select a city to be updated", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        Network networkToBeChanged = (Network) citiesNetworkTable.getValueAt(selectedRow, 1);
        String newNameChanged = (String) citiesNetworkTable.getValueAt(selectedRow, 0);
        if (util.notNullOrEmpty(newNameChanged)) {
            if (newNameChanged.equalsIgnoreCase(networkToBeChanged.getName())) {
                JOptionPane.showMessageDialog(this, "No change in name detected", "INFO", JOptionPane.INFORMATION_MESSAGE);
                return;
            } else {
                if (util.isValidName(newNameChanged)) {
                    for (Network network : ecoSystem.getNetworks()) {
                        if (network.getName().equalsIgnoreCase(newNameChanged)) {
                            JOptionPane.showMessageDialog(null, "City already exists. Please enter a new city!", "Error", JOptionPane.ERROR_MESSAGE);
                            cityNameTextField.setText("");
                            return;
                        }
                    }
                    System.out.println("Updating network name from :" + networkToBeChanged.getName() + " to :" + newNameChanged);
                    networkToBeChanged.setName(newNameChanged);
                    populateNetworkTable();
                    JOptionPane.showMessageDialog(null, "Sucessfully updated city network.", "INFO", JOptionPane.INFORMATION_MESSAGE);
                } else {
                    JOptionPane.showMessageDialog(null, "Please enter a valid city.", "Error", JOptionPane.ERROR_MESSAGE);
                }

            }
        } else {
            JOptionPane.showMessageDialog(this, "Please do not leave city name as empty!", "Error", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_updateBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backBtn;
    private javax.swing.JTable citiesNetworkTable;
    private javax.swing.JLabel cityNameLabel;
    private javax.swing.JLabel cityNameLabel1;
    private javax.swing.JTextField cityNameTextField;
    private javax.swing.JButton deleteBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton submitBtn;
    private javax.swing.JButton updateBtn;
    // End of variables declaration//GEN-END:variables
}
