/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.DoctorWorkspace;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Entity.Donor;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.DonorValidationWorkRequest;
import Business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ninos
 */
public class DoctorMainPage extends javax.swing.JPanel {

    /**
     * Creates new form DoctorMainPage
     */
    JPanel rightJPanel;
    Enterprise enterprise;
    UserAccount account;
    EcoSystem business;
    
    public DoctorMainPage(JPanel rightJPanel, Enterprise enterprise, UserAccount account, EcoSystem business) {
        initComponents();
        this.rightJPanel = rightJPanel;
        this.enterprise = enterprise;
        this.account = account;
        this.business = business;
        populateDonorValidationReqTable();
        doctorName.setText(account.getEmployee().getEmpName());
    }
    
    void populateDonorValidationReqTable(){
        DefaultTableModel model = (DefaultTableModel) validateWr.getModel();
        model.setRowCount(0);
        for(WorkRequest obj : enterprise.getWorkQueue().getWorkRequestList()){
            if(obj instanceof DonorValidationWorkRequest && (obj.getReceiver() == null || obj.getReceiver() == account)){
                DonorValidationWorkRequest finalobj = (DonorValidationWorkRequest) obj;
                Object[] row = new Object[6];
                row[0] = finalobj;
                row[1] = finalobj.getPatientId();
                row[2] = finalobj.getSender();
                row[3] = finalobj.getReceiver() == null ? "Unassigned" : finalobj.getReceiver();
                row[4] = finalobj.getStatus();
                row[5] = finalobj.getTestResult();
                model.addRow(row); 
            }
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        assignRequestToMeBtn = new javax.swing.JButton();
        displayEnterpriseLabel3 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        validateWr = new javax.swing.JTable();
        displayEnterpriseLabel4 = new javax.swing.JLabel();
        doctorName = new javax.swing.JLabel();
        goToTestingAreaBtn = new javax.swing.JButton();

        setBackground(java.awt.SystemColor.activeCaption);

        assignRequestToMeBtn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        assignRequestToMeBtn.setText("Assign Request To Me");
        assignRequestToMeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                assignRequestToMeBtnActionPerformed(evt);
            }
        });

        displayEnterpriseLabel3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        displayEnterpriseLabel3.setText("Doctor Home Page");

        validateWr.setBackground(java.awt.SystemColor.info);
        validateWr.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        validateWr.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Message", "Donor Id", "Sender", "Receiver", "Status", "Test Results"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(validateWr);
        validateWr.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);

        displayEnterpriseLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        displayEnterpriseLabel4.setText("Donor Validation Work Requests");

        doctorName.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        doctorName.setText("<DoctorName>");

        goToTestingAreaBtn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        goToTestingAreaBtn.setText("Go To Testing Area");
        goToTestingAreaBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                goToTestingAreaBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(164, 164, 164)
                        .addComponent(assignRequestToMeBtn)
                        .addGap(75, 75, 75)
                        .addComponent(goToTestingAreaBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(348, 348, 348)
                        .addComponent(displayEnterpriseLabel3)
                        .addGap(179, 179, 179)
                        .addComponent(doctorName))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 856, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(displayEnterpriseLabel4)))
                .addContainerGap(37, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(doctorName))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(displayEnterpriseLabel3)))
                .addGap(73, 73, 73)
                .addComponent(displayEnterpriseLabel4)
                .addGap(4, 4, 4)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(57, 57, 57)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(assignRequestToMeBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(goToTestingAreaBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(184, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void assignRequestToMeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_assignRequestToMeBtnActionPerformed
        // TODO add your handling code here:
        int selectedRowOfTable = validateWr.getSelectedRow();
        if (selectedRowOfTable < 0) {
            JOptionPane.showMessageDialog(null, "Please select a row to assign to yourself.", "INFO", JOptionPane.INFORMATION_MESSAGE);
            return;
        }
        DonorValidationWorkRequest wk = (DonorValidationWorkRequest)validateWr.getValueAt(selectedRowOfTable, 0);
        if(wk.getStatus().equalsIgnoreCase("Request Raised")){
            if(wk.getReceiver() == null){
                wk.setReceiver(account);
                wk.setStatus("Request Processing");
                Donor donorObj = wk.getDonorObj();
                donorObj.setDocAssignedEmaild(account.getUsername());
                donorObj.setIsDocAssigned(true);
                // refresh validation request table
                populateDonorValidationReqTable();
                JOptionPane.showMessageDialog(null, "Donor assigned to you for validation", "INFO", JOptionPane.INFORMATION_MESSAGE);
            }
        }else {
                JOptionPane.showMessageDialog(null, "Request already in process", "INFO", JOptionPane.INFORMATION_MESSAGE);
                return;
        }
    }//GEN-LAST:event_assignRequestToMeBtnActionPerformed

    private void goToTestingAreaBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_goToTestingAreaBtnActionPerformed
        // TODO add your handling code here:
        DoctorRequestPatientTestPanel dbObj = new DoctorRequestPatientTestPanel(rightJPanel, enterprise, account, business);
        rightJPanel.add("doctorActivity", dbObj);
        CardLayout layout = (CardLayout) rightJPanel.getLayout();
        layout.next(rightJPanel);
    }//GEN-LAST:event_goToTestingAreaBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton assignRequestToMeBtn;
    private javax.swing.JLabel displayEnterpriseLabel3;
    private javax.swing.JLabel displayEnterpriseLabel4;
    private javax.swing.JLabel doctorName;
    private javax.swing.JButton goToTestingAreaBtn;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable validateWr;
    // End of variables declaration//GEN-END:variables
}
