/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.DoctorWorkspace;

/**
 *
 * @author Amey
 */
public class DoctorRequestPatientTestPanel extends javax.swing.JPanel {

    /**
     * Creates new form DoctorRequestPatientTestPanel
     */
    public DoctorRequestPatientTestPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bloodTestCheckbox = new javax.swing.JCheckBox();
        cancerCheckbox = new javax.swing.JCheckBox();
        askToTakeTestButton = new javax.swing.JButton();
        patientEmailDropdownLabel = new javax.swing.JLabel();
        patientNameCombobox = new javax.swing.JComboBox();
        testCheckboxLabel = new javax.swing.JLabel();
        xrayCheckbox = new javax.swing.JCheckBox();
        radiologicTestCheckbox = new javax.swing.JCheckBox();
        gynecologicalScreeningCheckbox = new javax.swing.JCheckBox();
        checkResultStatusButton = new javax.swing.JButton();
        testResultSectionHeaderLabel = new javax.swing.JLabel();
        patientTestSectionHeaderLabel = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        testSelectionHeaderLabel = new javax.swing.JLabel();

        setBackground(java.awt.SystemColor.activeCaption);

        bloodTestCheckbox.setBackground(new java.awt.Color(255, 255, 255));
        bloodTestCheckbox.setFont(new java.awt.Font("Times New Roman", 1, 23)); // NOI18N
        bloodTestCheckbox.setText("Blood Test");

        cancerCheckbox.setBackground(new java.awt.Color(255, 255, 255));
        cancerCheckbox.setFont(new java.awt.Font("Times New Roman", 1, 23)); // NOI18N
        cancerCheckbox.setText("Cancer Screening");

        askToTakeTestButton.setBackground(new java.awt.Color(153, 204, 255));
        askToTakeTestButton.setFont(new java.awt.Font("Times New Roman", 1, 23)); // NOI18N
        askToTakeTestButton.setText("Ask To Take Test");
        askToTakeTestButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        askToTakeTestButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                askToTakeTestButtonActionPerformed(evt);
            }
        });

        patientEmailDropdownLabel.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        patientEmailDropdownLabel.setText("Patient Information");

        testCheckboxLabel.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        testCheckboxLabel.setText("Tests");

        xrayCheckbox.setBackground(new java.awt.Color(255, 255, 255));
        xrayCheckbox.setFont(new java.awt.Font("Times New Roman", 1, 23)); // NOI18N
        xrayCheckbox.setText("Chest X-Ray and Electrocardiogram (EKG)");

        radiologicTestCheckbox.setBackground(new java.awt.Color(255, 255, 255));
        radiologicTestCheckbox.setFont(new java.awt.Font("Times New Roman", 1, 23)); // NOI18N
        radiologicTestCheckbox.setText("Radiologic Testing");

        gynecologicalScreeningCheckbox.setBackground(new java.awt.Color(255, 255, 255));
        gynecologicalScreeningCheckbox.setFont(new java.awt.Font("Times New Roman", 1, 23)); // NOI18N
        gynecologicalScreeningCheckbox.setText("Gynecological screening");

        checkResultStatusButton.setBackground(new java.awt.Color(153, 204, 255));
        checkResultStatusButton.setFont(new java.awt.Font("Times New Roman", 1, 23)); // NOI18N
        checkResultStatusButton.setText("Click to Check Result Status");
        checkResultStatusButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        checkResultStatusButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkResultStatusButtonActionPerformed(evt);
            }
        });

        testResultSectionHeaderLabel.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        testResultSectionHeaderLabel.setText("Test Result Section");

        patientTestSectionHeaderLabel.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        patientTestSectionHeaderLabel.setText("Patient Information Section");

        testSelectionHeaderLabel.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        testSelectionHeaderLabel.setText("Test Selection Panel");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(testCheckboxLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(xrayCheckbox, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(askToTakeTestButton, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(radiologicTestCheckbox)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(gynecologicalScreeningCheckbox))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(bloodTestCheckbox, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(48, 48, 48)
                                            .addComponent(cancerCheckbox, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(0, 416, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(testResultSectionHeaderLabel)
                            .addComponent(patientTestSectionHeaderLabel)
                            .addComponent(checkResultStatusButton, javax.swing.GroupLayout.PREFERRED_SIZE, 347, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(patientEmailDropdownLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(patientNameCombobox, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addComponent(jSeparator1)
            .addGroup(layout.createSequentialGroup()
                .addGap(356, 356, 356)
                .addComponent(testSelectionHeaderLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(testSelectionHeaderLabel)
                .addGap(27, 27, 27)
                .addComponent(patientTestSectionHeaderLabel)
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(patientNameCombobox, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(patientEmailDropdownLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(testCheckboxLabel)
                    .addComponent(bloodTestCheckbox)
                    .addComponent(cancerCheckbox))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(radiologicTestCheckbox)
                    .addComponent(gynecologicalScreeningCheckbox))
                .addGap(31, 31, 31)
                .addComponent(xrayCheckbox)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(askToTakeTestButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addComponent(testResultSectionHeaderLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                .addComponent(checkResultStatusButton, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(65, 65, 65))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void askToTakeTestButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_askToTakeTestButtonActionPerformed

    }//GEN-LAST:event_askToTakeTestButtonActionPerformed

    private void checkResultStatusButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkResultStatusButtonActionPerformed

    }//GEN-LAST:event_checkResultStatusButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton askToTakeTestButton;
    private javax.swing.JCheckBox bloodTestCheckbox;
    private javax.swing.JCheckBox cancerCheckbox;
    private javax.swing.JButton checkResultStatusButton;
    private javax.swing.JCheckBox gynecologicalScreeningCheckbox;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel patientEmailDropdownLabel;
    private javax.swing.JComboBox patientNameCombobox;
    private javax.swing.JLabel patientTestSectionHeaderLabel;
    private javax.swing.JCheckBox radiologicTestCheckbox;
    private javax.swing.JLabel testCheckboxLabel;
    private javax.swing.JLabel testResultSectionHeaderLabel;
    private javax.swing.JLabel testSelectionHeaderLabel;
    private javax.swing.JCheckBox xrayCheckbox;
    // End of variables declaration//GEN-END:variables
}
